hide_download: true
hide_download_original: null
leftnav:
- identifier: a907fdd7-f693-6e16-e921-9e0afb3121c0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 43962b4d-93fc-7256-fded-97a356929aab
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: d39237d6-2cc8-05c5-659d-330a0c0cf7ad
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: b07e8fbb-d1ad-33cb-77ac-1d5e3ab39afe
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 3a1b85fb-e03d-d032-d5a6-f7407f9c98b6
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 50
